### ISSUE TITLE
Call to a member function getInterval() on null

### ISSUE THREAD

**Issue by simontryathome** [osiset/laravel-shopify#1043]
Hi osiset,

First of all, thank you very much for such amazing work.
I am using your app almost everything working very smoothly.

**Problem** 
I am trying to create a billing URL and at that time i got this error.

I have added 0 on on_install in the database plan. so now when i try to install the app it will be redirected to the may setting area and this error happening.

![image](https://user-images.githubusercontent.com/96615983/147343640-7ec55c1e-ea49-4fb9-9968-11b0932762fa.png)

i am using ngrok.

can you please let me know why this happens application working with on_install = 1 perfectly .

Thank you

**Comment by PrajapatiAakash** [comment]
Hello @osiset 

I have checked the above issue and I have found that there is no condition for on_install value is 0 so what happens when the app is installed after redirecting to the dashboard URL and after goes into the billing middleware and billing middleware check any app charges found if no then redirect to the billing route which is below:

![image](https://user-images.githubusercontent.com/35802146/147365040-3f85dabc-a9aa-46ca-b96f-f7ad01eca9ab.png)

so when this URL execute then it comes to the billing controller which is called the index method and in the index method it's called the $getPlanUrl and in this method not found any plan so the $plan variable value is null and this variable is called the getInterval() method so it's giving error.

so please find the full tracking details:

![image](https://user-images.githubusercontent.com/35802146/147365396-1eb53d15-16be-47ce-b6d5-195440f8a013.png)

-> osiset\laravel-shopify\src\Traits\BillingController.php:49
-> \vendor\osiset\laravel-shopify\src\Actions\GetPlanUrl.php:73

Based on my full investigation I have found that needs to add some condition related to on_install value is 0.

**Comment by DanielChritisan** [comment]
Hello @osiset 

I have checked the above issue and I have found that there is no condition for on_install value is 0 so what happens when the app is installed after redirecting to the dashboard URL and after goes into the billing middleware and billing middleware check any app charges found if no then redirect to the billing route which is below:

![image](https://user-images.githubusercontent.com/35802146/147365040-3f85dabc-a9aa-46ca-b96f-f7ad01eca9ab.png)

so when this URL execute then it comes to the billing controller which is called the index method and in the index method it's called the $getPlanUrl and in this method not found any plan so the $plan variable value is null and this variable is called the getInterval() method so it's giving error.

so please find the full tracking details:

![image](https://user-images.githubusercontent.com/35802146/147365396-1eb53d15-16be-47ce-b6d5-195440f8a013.png)

-> osiset\laravel-shopify\src\Traits\BillingController.php:49
-> \vendor\osiset\laravel-shopify\src\Actions\GetPlanUrl.php:73

Based on my full investigation I have found that needs to add some condition related to on_install value is 0.

**Comment by Kyon147** [comment]
Hi both,

Do you have any plans in the `plans` table? 

I've seen similar errors when no correct plans have been set up. There needs to be at least on "on_install" plan if you have billing enabled.

**Comment by Kyon147** [comment]
As there's been no update in a while, closing ticket. Reopen if needed.
