### ISSUE TITLE
Proxy App URL downloading the file instead of rendering

### ISSUE THREAD

**Issue by BhuvneshSoniApporio** [osiset/laravel-shopify#1082]
When i change the content type into application/liquid . It download the file instead rendering. What possible changes i need to do for that. I am using osiset package to crate shopify app. And using laravel 7.4 version. I am using below code for the proxy url response.

Route::get('/proxy', function () {
return response('Hello, world!')->withHeaders(['Content-Type' => 'application/liquid']);
})->middleware('auth.proxy');

**Comment by asherm2** [comment]
Hey @BhuvneshSoniApporio 

https://github.com/osiset/laravel-shopify/wiki/App-Proxies#browser-downloads-liquid

**Comment by BhuvneshSoniApporio** [comment]
Hii @asherm2 
Thank you for your response.

I have checked the provided solution, But still its not working.

**Comment by Kyon147** [comment]
Without more context we can't offer any other advice that is not already in the link above. 

Usually it is because of what Oiset has put in the wiki because of the redirect. You should check the `network` tab in dev tools and see if you are getting a 301 or 302 when trying to access the proxy page.
