### ISSUE TITLE
Oauth error invalid_request - where to set redirect_uri and application url?

### ISSUE THREAD

**Issue by codeoutin** [osiset/laravel-shopify#1144]
## Expected Behavior

I'm trying to set up Laravel 8 with laravel-shopify but got stuck since Shopify seems to changed the App Interface

## Current Behavior

I created login.blade.php and according routes but after i send the form i'm redirected to a shopify page that says
´Oauth error invalid_request: The redirect_uri and application url must have matching hosts´

I never got the option to set Application URL and Redirect URL like in the Install Page meantioned because these options are not there in Shopify App Panel. There is no App-Setup like on all the screenshots, what am i doing wrong?

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.1
* Laravel Version: v8.75
* PHP Version: v8.1.5
* Using a toolset (Docker, Laradock, Vagrant, etc.): DBngin

**Comment by inaryu** [comment]
@codeoutin 

Are you talking about the content of the problem on the Shopify side that prevents setup? Or are you talking about the content of the problem on the laravel-shopify side?

**Comment by Kyon147** [comment]
Do you have a shopify partners account? It sounds like you need to set up your app in the partners account and it is also worth mentioning a login page was removed as Shopify don't like them being used as you need to login via their admin if you are an embedded app which this package is. 

Sounds like a setup issue, rather than a package one so closing this ticket but open a discussion in the Discussion tab if you want someone to help.
