### ISSUE TITLE
Middleware Issue

### ISSUE THREAD

**Issue by yogeshausp** [osiset/laravel-shopify#1190]
Middleware( middleware(['verify.shopify'])) did not work when we get data from table.

![Screenshot_1](https://user-images.githubusercontent.com/99256150/186071799-8e2e2fc7-b6ca-491c-babf-51ff956dcac8.png)
![Screenshot_2](https://user-images.githubusercontent.com/99256150/186071804-02967772-886b-4676-8cae-bf1f24a320b6.png)
![Screenshot_3](https://user-images.githubusercontent.com/99256150/186071807-9da1b972-5f68-4674-8264-9a3a08817adb.png)
![Screenshot_4](https://user-images.githubusercontent.com/99256150/186071809-fea52b42-b599-4585-b02e-b5fd6ea3fa87.png)
![Screenshot_5](https://user-images.githubusercontent.com/99256150/186071810-f48ef915-81f7-460b-9e3e-a91e3d76ddce.png)

**Comment by Kyon147** [comment]
@yogeshausp - Looking at your samples, it does not look like a package issue like @enmaboya mentions.

`verify.shopify` is to verify a shop within the app itself and it loads the user into the session to you can use things like `Auth` to grab the current user.

You API request is failing because you are trying to authenticate that request with the shopify middleware. Also, out of good practice you should be using `api.web` for api requests not `web.php` which is usually used for the app routing.

Closing this as it does not look like an app package issue.
