### ISSUE TITLE
When can we expect new release?

### ISSUE THREAD

**Issue by devpammy** [osiset/laravel-shopify#1196]
Hello @osiset and @all admins
When we can expect new release with laravel 9 support.

Thanks

**Comment by Kyon147** [comment]
The release for laravel 9 is in progress. 

We are working to make sure the next release also has some needed updates on top of laravel 9 support.

Thanks for your patience.

**Comment by akshay-praella** [comment]
@osiset 

First of all, I appreciate this package and all the effort on this. We are using this package since more than 4 years. May be since OhMyBrew version 4 or 5.

We are also want to integrate this in our new project. But the only issue is Laravel 9 support. We have launch date at 12th Sept. So, can we get the Laravel 9 supported version release ASAP?

Thanks

**Comment by Kyon147** [comment]
Hi @akshay-praella 

Laravel 9 is merged into master at the moment but there is not an official release yet. I'll be working on getting a release out hopefully this week but no promises on the date.
