### ISSUE TITLE
Billing Charge Deline 

### ISSUE THREAD

**Issue by dhruvbhavsar16** [osiset/laravel-shopify#148]
Hello, Some day ago In my shopify app when i was declining my recurring charge so it was redirecting to "billing/process" route as mentioned. But Suddenly it was not redirecting on "billing/process" when i am declining the billing charge just going on to apps and one pop up is coming of charge decline.I have tried to make a new billing plan and even i have done whole process but it still not going on "billing/process" when i'm declining the billing charge.

here are screenshots of that billing charge and that pop up messages.
![screenshot 347](https://user-images.githubusercontent.com/26164295/49590136-11dbed00-f991-11e8-89cb-a382d7f36abe.png)
![screenshot 348](https://user-images.githubusercontent.com/26164295/49590137-11dbed00-f991-11e8-9d8a-f60c2509b919.png)

App Link:

**Comment by dhruv728462** [comment]
As in your code when someone decline billing charge so it will redirect to error page that "You have decline billing charge". It's not redirecting on that page when i'm declining the billing charge.

**Comment by ohmybrew** [comment]
Yeah Shopify will kick you out if you decline actually... But I'm sure it triggers the internal page some how I just can't remember for what case

**Comment by dhruv728462** [comment]
But why i mean i have just change the billing decline page layout nothing else and i have try to debug by return "Hello";  on "BillingControllerTrait.php/process"  function.

After decline charge that is not trigger on "billing/process" it is going on "/admin/apps" of shopify panel.

**Comment by ohmybrew** [comment]
Yes that's Shopify's doing, not the package :/

On Dec. 6, 2018 23:53, "Dhruv Bhavsar" <notifications@github.com> wrote:

But why i mean i have just change the billing decline page layout nothing
else and i have try to debug by return "Hello"; on
"BillingControllerTrait.php/process" function.

After decline charge that is not trigger on "billing/process" it is going
on "/admin/apps" of shopify panel.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ohmybrew/laravel-shopify/issues/148#issuecomment-445122429>,
or mute the thread

**Comment by hakimihamdan88** [comment]
is this related? https://ecommerce.shopify.com/c/api-announcements/t/upcoming-change-declined-app-charge-redirects-will-now-be-handled-by-shopify-550516

**Comment by ohmybrew** [comment]
Oh wow, yes... ok then if thats the case theres nothing I can do.

I'll have to remove the decline flow and wiki docs on my side since its gone :/

Will update.

**Comment by ohmybrew** [comment]
Commit b5ae262 should fix this, need to physically test shortly.
