### ISSUE TITLE
How to change/upgrade scripttags when app is already installed

### ISSUE THREAD

**Issue by aledelgo** [osiset/laravel-shopify#368]
I've installed the app in my store with a scripttag.
Now i want upgrade it and add some scripttag (i would also remove some old scripttag but i can empty the old script if not else).

If i simply reauthenticate the app deleting the shop in my DB the install script job is not executed again (as i think it is already installed on the shopify side).

Probabily it would work if i change scopes of the app that force shopify to entirely reauthenticate the app, but i dont think it is a good idea.

How could i force reinstallation of scripttags for the app (only for shops that did't it already)?

Note: probably an app versioning strategy would be great, not found anything in docs but i'm asking to avoid reinventing the wheel

thanks

**Comment by Kyon147** [comment]
If you edit the script tag or add another it will be added automatically to the store. You can tidy up the old script tags but they won't do anything if you don't have them on the app anymore.

I have 3 script tags installed on local at the moment because of ngrok needing a different URL each time. The old ones don't affect anything and the user won't see them. 

Part of the after auth jobs is to check to make sure all the script tags are installed and install any new ones. So they should have them, if not, the next time they need to be authenticated they will or you can force it by redirecting them to /authenticate/
