### ISSUE TITLE
Class auth.shop does not exist

### ISSUE THREAD

**Issue by test-smartdesigns** [osiset/laravel-shopify#376]
Hi @ohmybrew 

 Error  'Class auth.shop does not exist', started to appear on the app that worked fine previously. 
"php": "^7.1.3",
"laravel/framework": "^5.8.0",
"ohmybrew/laravel-shopify": "^2.3"

**Comment by Kyon147** [comment]
Try changing your composer to "ohmybrew/laravel-shopify": "^10.0.0" and running `composer update`

**Comment by test-smartdesigns** [comment]
@Kyon147  Now got stuck on issue 'Unable to verify signature'

**Comment by Kyon147** [comment]
That's an ongoing issue which is being resolved which you can temp fix by
swapping composer to point to "dev-master"

**Comment by test-smartdesigns** [comment]
@Kyon147 Not working even on using "ohmybrew/laravel-shopify": "dev-master"

**Comment by jedimdan** [comment]
You might need to update your app since you were using a version that's almost 2 years older than what is the latest release. It would be good to study the diff between these two versions: https://github.com/ohmybrew/laravel-shopify/compare/v2.3.2...v10.1.0 

I would suggest starting by [comparing your `config/shopify-app.php` with the latest version](https://github.com/ohmybrew/laravel-shopify/compare/v2.3.2...v10.1.0#diff-0ea37247409d5566adf1a3bfe24ed34c) as some new config options have been added since and some have been removed.

**Comment by test-smartdesigns** [comment]
@jedimdan How to update app to the latest version ? Composer updated to "ohmybrew/laravel-shopify": "^10.0.0" along with 'composer update' command.

**Comment by jedimdan** [comment]
@test-smartdesigns What I meant was that you need to update your code to make sure that it is compatible with the newest version of the library. Which is why I suggested looking at the config files as a start. You may also consider going through the setup guides again in case anything has changed in the past few years.
