### ISSUE TITLE
Creating a page using API

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#408]
Hi,

I just want to create a page for Shopify where I will show all products and filters (search by name, by price...)

Please give me an idea of how to do that?

- Take all products using API -> store in my database -> create grid view from JSON data -> implement my view in the Shopify page in iFrame? Is that correct?

Is that correct or I need to use something other?

**Comment by APdevelopments** [comment]
Or i need to include js file which will create content dinamicly?

**Comment by Kyon147** [comment]
Hi @APdevelopments 

The issue section is for bugs and problems with the package, it's not really used for general advice on how to code unless it is a specific question on an internal function usually.

You need to learn more about Laravel rather than this package specifically, using Blade templates or VUEJS depending on how you want to do it.

**Comment by APdevelopments** [comment]
Ok. Thanks. I know everything about Laravel and blade templates but how to show blade template into Shopify page? Is that possible? Please some advice...
