### ISSUE TITLE
Release of dev-master having Samesite cookie issue fixes

### ISSUE THREAD

**Issue by faisal-saeed-brainx** [osiset/laravel-shopify#413]
Hi @osiset, @jedimdan 

First of all many many thanks to all of you for your contribution in this project.

I have used this project to build an embedded shopify app. In Feb 2020, I upgraded the package to the 10.3.1 due to samesite cookie issues. After this upgrade I am continuously facing some issues like "Unable to get shop domain.". It seems that this has been fixed in the dev-master branch, but this branch does not have samesite cookies issue fixes. 

So could you please give me an idea about when you guys have planned to make a release of this dev-master branch having samesite cookie issue fixes.

Thanks in advance
Faisal Saeed

**Comment by osiset** [comment]
Unit/functional testing is complete.Physical tests are going well, I have many many edge cases I have to test for so I am hoping by end of next week or week after I can release it.If that solves your questions please close the issue :)On Mar. 12, 2020 12:20, Faisal Saeed <notifications@github.com> wrote:
Hi @osiset, @jedimdan
First of all many many thanks to all of you for your contribution in this project.
I have used this project to build an embedded shopify app. In Feb 2020, I upgraded the package to the 10.3.1 due to samesite cookie issues. After this upgrade I am continuously facing some issues like "Unable to get shop domain.". It seems that this has been fixed in the dev-master branch, but this branch does not have samesite cookies issue fixes.
So could you please give me an idea about when you guys have planned to make a release of this dev-master branch having samesite cookie issue fixes.
Thanks in advance
Faisal Saeed

**Comment by faisal-saeed-brainx** [comment]
Thank you for your kind response. I am closing this issue and will wait for your next release.

**Comment by jedimdan** [comment]
@faisal-saeed-brainx I've personally not experienced this myself. Just out of curiosity, can you share with us in what scenario does this occur, and what is the fix that's in the `master` branch that addressed it? 

Glad that @osiset know's what you're talking about, but I think it's useful for the rest of us to know as well, so we can find out if we have the same problem.

**Comment by KonradMil** [comment]
@jedimdan 
As I am facing issue with cookies myself, I found this.
https://github.com/osiset/laravel-shopify/pull/382
