### ISSUE TITLE
When installing app redirect me to my domain instead display app into Shopify admin UI

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#452]
When I install my app it redirects me to my domain instead display app into SHopify admin UI...

User flow:

_1. go to example.com/login to enter the shop name
2. redirected to Shopify to install the app
3. from Shopify redirected again to my domain -> this is the problem - I want user to stay at Shopify admin UI and use my app from their admin panel._

How I can fix that?

I'm using:
* Laravel 5.8
* osiset/laravel-shopify 11.3
* PHP 7.3

```
Here is my first page:
@extends('layouts.app')

@section('content')
   
<main class="container">
//MY CONTENT
</main>

@endsection


@section('scripts')
    @parent

    <script type="text/javascript">
        var AppBridge = window['app-bridge'];
        var actions = AppBridge.actions;
        var TitleBar = actions.TitleBar;
        var Button = actions.Button;
        var Redirect = actions.Redirect;
        var titleBarOptions = {
            title: 'Welcome',
        };
        var myTitleBar = TitleBar.create(app, titleBarOptions);
    </script>
@endsection
```

How to show my app into Shopify admin interface ? I dont want to be redirected to my domain

**Comment by awebartisan** [comment]
Hi there. You need to `createApp` and provide `forceRedirect: true`.

Have a look at the default layout included in the package here : [https://github.com/osiset/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php](https://github.com/osiset/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php)

**Comment by awebartisan** [comment]
Hi there. You need to `createApp` and provide `forceRedirect: true`.

Have a look at the default layout included in the package here : [https://github.com/osiset/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php](https://github.com/osiset/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php)

**Comment by osiset** [comment]
forceRedirect is already true in my default layout... I see your view is not using it, its using its own.

Are you extending the packages internal layout file or using your own?

**Comment by manpreet396** [comment]
When installing app redirect me to my domain instead display app into Shopify admin ..
Can you please help me to solve this issue??

**Comment by awebartisan** [comment]
@manpreet396 you're creating an external app? which should not be embedded into shopify admin?

**Comment by manpreet396** [comment]
@awebartisan I am creating embedded app, first time when I install then only it goes to outside https://(your-domain).com/login after that it opened in shopify admin UI.

**Comment by manpreet396** [comment]
Can anyone please help me to solve this issue??

**Comment by awebartisan** [comment]
Hey @manpreet396 , not sure if I understand correctly.

Here's what's expected behaviour with an Embedded app:
- User goes to Shopify store, provide their domain
- They're redirected to the "installation screen" where they approve the installation
- After that your app is installed
- Next time they go to your app from Shopify Admin, they will just be redirected to your dashboard because the package takes care of Authentication and stuff
- In case your app is not published and you're working on local, first time you go though `/login` , that will install the app on the store
- After the installation, next time you click on App name inside Shopify admin, it will just redirect you the app dashboard inside Shopify Admin ( because it is embedded )
- Again, authentication is handled by the package behind the scenes after the first time installation.
