### ISSUE TITLE
How can we get Access Token to use in shopify APIs

### ISSUE THREAD

**Issue by jimmy818** [osiset/laravel-shopify#473]
Hi I am new to creating shopify app, can you guys please guide me how can I get access token of storefront which I will use to call Shopify APIs

**Comment by Kyon147** [comment]
You don't need to. 

The API is built into the package and you just need to call `Auth::user()->api()`

Please read the wiki as it has all the basics. https://github.com/osiset/laravel-shopify/wiki/Usage

**Comment by burfbari** [comment]
Hi, I have a related question.
We have the following in the User table:
- Shop Name
- Shop Email
- Password
As I understand, once implemented properly, we can make API calls to show the data inside the Shopify App Bridge. How do we use the above information if we want to call the Shopify API from outside of the App Bridge?

**Comment by Kyon147** [comment]
Hey @burfbari 

AppBridge and the API calls are slightly different things. AppBridge is just a JavaScript package that handles the app within the browser such as loading it within the iFrame and giving access to methods to update the route in the breadcrumbs, show toasts etc.

I'm not sure your exact requirements but to access the API for a store, you just need to call the `Auth::user()->api()` like above in the previous question.

**Comment by BhuvneshSoniApporio** [comment]
Hello @Kyon147 

Is it required to hold shop entry into users table. Suppose we are using users table for laravel project access, then why we add dump entry into this. Is there any option of that. 
Secondly, If i want access shopify shop data like orders in laravel project, Then how we access those data, because shop user that authenticate shopify shop and another laravel application logged in user also belong to same table then how we manage this. And how we get orders data without access token.

Thank you.

**Comment by Kyon147** [comment]
> Hello @Kyon147
> 
> Is it required to hold shop entry into users table. Suppose we are using users table for laravel project access, then why we add dump entry into this. Is there any option of that. Secondly, If i want access shopify shop data like orders in laravel project, Then how we access those data, because shop user that authenticate shopify shop and another laravel application logged in user also belong to same table then how we manage this. And how we get orders data without access token.
> 
> Thank you.

Hey @BhuvneshSoniApporio 

Yeah as of v13 (I think) it was changed so that this package has a closer inner logic to how Laravel runs it's authentication. This had a few big benefits around stuff like broadcasting etc which uses the User model to authenticate against. 

If you use your users table for normal laravel auth as well - like admin users logging in - you should be fine to use them side by side but might want to add an additional column which is like a "user type" i.e shop vs user. This way you get the benefit of both worlds. 

As mentioned above, you access the Shopify api using `Auth::user()->api()` with the API method being one of the methods from the Shop Interface.

You can't get any Shopify information without an access token, you'd need to make sure you "shops" always go through the authentication process this app handles.

**Comment by BhuvneshSoniApporio** [comment]
Hello @Kyon147 
Thanks for your response. 

Could you please give me answer of below questions.
How to verify Shop on another page not inside shopify iframe ?

As i already told you that i am using same table for laravel auth, So let me know how can i authenticate user as well for laravel auth with shopify authentication when user install the shopify app. what you suggest for that. 

According to my project architecture, What i need to do is, When user install my app, first authenticate the shop, then redirect to my login page then user login here, then it use previously authenticated shop and store the access code of that. So i can access the shop orders in future when its required. 

So please help me on this.

**Comment by Kyon147** [comment]
If the user installs your app via Shopify you should already have the token needed to access the shops orders.

**Comment by BhuvneshSoniApporio** [comment]
@Kyon147 
Let me know where i can assign other columns values for shop.

**Comment by Kyon147** [comment]
@BhuvneshSoniApporio I'm not quite sure what you are trying to achieve to be completely honest. 

If you use `users` table to also access an "admin" for the app but also the "shops" use `users`as part of this package then as I have mentioned before. You should be able to still use users in the traditional way (from what I know but not tested) as this package just extends on top of the user and the user auth flow.

When people install your app through the shopify store, they will trigger the `/authenticate` route which will save them as a "store" in the users table. The `verify.shopify` middleware is the thing that acts as the gate for those shops. Just like `auth` middleware can be used for the normal "users" as the table entries are basically pretty similar baring a couple extra columns added like `plan_id` etc.

So you can just use different middleware to stop shops / users accessing parts of your app however you see fit. Adding in the extra column was just one suggestion to help easily segment "shops" from "admin users" but it really depends on your specific use case as that sits outside the scope of this package.

As this is not really the place to ask for business logic advice on how to build your app I'd suggest you ask the question on [StackOverflow](https://stackoverflow.com/) or something similar as this is to deal with issues with the package. 

Good luck in building your app!

**Comment by BhuvneshSoniApporio** [comment]
Hello Osiset/Laravel-Shopify,

I am not able to redirect to another page after shop authentication. Could
you please help on this.
