### ISSUE TITLE
After decline the charges script tag is still working.

### ISSUE THREAD

**Issue by manishbanda** [osiset/laravel-shopify#501]
I am using your ohmybrew laravel shopify 10.3 version package, and in my app after first app was free so multiple store installed that app, then i made it chargable, so after that, some of the store decline the charge, but still the script tag is working on them store and app is performing, only that, admin is not able to access the app dashboard from apps section, but script tag is working.
Please help me to out this.

**Comment by Kyon147** [comment]
This is not really the place for this sort of question as it is more a bespoke issue than a package one.

Script tags are uninstalled automatically when a store uninstalls an app but because your app now uses the billing middleware, those who were using it for free and now locked out from what I can tell by your comments.

To solve your issue, just add a check in the script tag to make sure they are a paying store. So whatever API call you are making to do whatever logic, add in a boolean for "paid" or something and if that is false, don't execute your script tag.

That way, those stores who have your "free" version installed but have not upgraded to paid can't use it on the frontend.

Hope this gives you some idea on what to do. Closing this to keep the issues queue tidy.
