### ISSUE TITLE
Proxy is redirecting to my server's /proxy URL

### ISSUE THREAD

**Issue by skillmatic-co** [osiset/laravel-shopify#507]
I've created a proxy app, but I'm having an odd issue.

In my routes I have:

```
Route::get('/proxy', 'AppProxyController@index')->middleware('auth.proxy');
```

In `AppProxyController.php` I have:

```
public function index()
{
    return response('Hello, world!', 200);
}
```

For some reason when I go to https://example.myshopify.com/apps/my-app, it's redirecting to https://example.com/proxy with all of the request variables in the URL (shop, signature, timestamp, etc). My "Hello, world!" is shown fine there, but this should not be redirecting, but instead showing that within the Shopify site.

Anyone have any idea why this is happening?

**Comment by skillmatic-co** [comment]
Digging in, I think it has something to do with HTTPS.

I can't even visit my https ngrok URL, I get a 301 to the non-https URL.

**Comment by osiset** [comment]
It needs to be HTTPs, ngrok hardly works for anyone using this package.. it just doesn't work out for some reason.

Try without ngrok, like on Heroku or someother public dev environment.

**Comment by lagunasolutions** [comment]
@skillmatic-co I'm having the same problem. Is deploying on a public environment working for you?

**Comment by skillmatic-co** [comment]
@lagunasolutions Sorry, I abandoned the Laravel route and went with Rails.

**Comment by lagunasolutions** [comment]
@skillmatic-co @osiset 

I manage to make it work fine with ngrok ( I have a paid account not sure if it would work otherwise )

Here is what I had to do, hopefully it would help some people:

Here is the ngrok command I use
`ngrok http -host-header=rewrite -subdomain=mysubdomain mylocaldomain.local:80`

Here is the htaccess file I use (this was the culprit of having shopify redirecting the proxy url since the URL wasn't secure.

`<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On
    # Addition: Force SSL
    RewriteCond %{HTTP:X-Forwarded-Proto} !https
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>`

I also went in the "About" link in my installed shopify app to use a custom proxy url (just to make sure the other was wasn't cached by the browser or causing any other caching issue).

Working good so far!

@osiset btw thanks for the good work
