### ISSUE TITLE
webhook not working

### ISSUE THREAD

**Issue by Adebayo120** [osiset/laravel-shopify#541]
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Expecting webhook to receieve request data but non is received job not even initiated

## Current Behavior

laravel project not receiving corresponding webhook action on shop

## Failure Information

no failure info given

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. followed guid on how to set up webhook ran the command "php artisan shopify-app:make:webhook ProductsCreateJob products/create" and added the correllative array in shopify-app.php
2.     'webhooks' => [
        [
            'topic' => 'products/create',
            'address' => 'https://your-domain.com/webhook/products-create'
        ]
    ],
3. no webhook response

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: vX.Y.Z
* Laravel Version: vX.Y.Z
* PHP Version: vX.Y.Z
* Using a toolset (Docker, Laradock, Vagrant, etc.):

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment]
There's a couple of reasons webhooks tend to not work and one of them is using a local tunnel service such as ngrok. I would try it in a development server rather than your local and see if it works.

The other reason is the webhook manager is fired from a queue if you have set up a queue which is not "sync" i.e. fires straight away make sure the queue worker is running otherwise the job never gets completed.

**Comment by Adebayo120** [comment]
thank you very much for the explanation, have been able get the reason why it wasn't working, the queue was running alright, i was using valet to test the app on my local since valet runs on nginx, thought shopify should be able to connect to it as my webhook endpoint uri but for one reason i don't know it didn't work, had to configure ngrok and 😁 its now working well, but don't know if you can put me through why was ngnix not enough to connect to my local, once again thanks for the time

**Comment by osiset** [comment]
Not sure I follow what you're fully saying, but I'll try to explain how it works.

As @Kyon147 mentioned it depends on the setup you've done (sync, ngork, etc).

Why simply using Valet on its own is not enough is because Shopify doesn't know who you are. If you had a webhook that had a url of "http://localhost/webhook/orders-create", Shopify would try to send webhook data to that URL.

Since "localhost" is local, Shopify would be attempting to send it to itself, not to your app.
Flow would be: Shopify => "localhost" => Shopify... fail

When you use something like ngrok, it gives you a public-facing URL which tunnels information to your computer's IP.
Flow would be: Shopify => "ngrok url" => "your IP"... success.

However ngrok is hit and miss in my experience and many other on here, not sure of the full reason but it appears to be an issue from going from https to http when transmitting the data.

I'll close for now as you have it working!

**Comment by jclark-vanish** [comment]
I am also having an issue with this.  Using ngrok.  Response is "401 Unauthorized".  I am assuming this is just the signing issues, but not sure whats up.  Any thoughts?

**Comment by Adebayo120** [comment]
as you've noticed 401 unauthorized response denotes that you are having an authentication issue, i'll advice you to check your auth token well for assurance

**Comment by Kyon147** [comment]
@jclark-vanish please create your own issue if you are having a problem with the app. That way you can fill in the bug sheet and we can help provide you with better feedback.
