### ISSUE TITLE
opening an application in a separate window

### ISSUE THREAD

**Issue by Enmaboya** [osiset/laravel-shopify#583]
How do I open an application in a separate window instead of in an iframe?

I can change the property of the app in default.blade.php
"forceRedirect: false", and redirect the parent window to the application url.

but in this case there are one problem -  I still have the application in iframe for a while and only then redirect occurs.

is there any solution to this problem ?

**Comment by osiset** [comment]
Its been a very long time since I've done an external one.

I think if you set SHOPIFY_APPBRIDGE_ENABLED=0 in your .env it should be fine. This would remove all appbridge JS.

Additionally, you may need to check if you're still inside an iframe... you can do this with `window.location !== window.parent.location`. If thats true, then you're inside the iframe and you can issue a fullpage redirect to your full domain.
