### ISSUE TITLE
Preferred way to access Shop API in job

### ISSUE THREAD

**Issue by justenh** [osiset/laravel-shopify#609]
What is the preferred way to access the Shop API during a cron job?

Also, is there a particular test file that has a good example of testing against the API? I'd like to write a feature test that stubs the return of the `/admin/api/2020-10/customers/` endpoint. Any suggestions would be greatly appreciated!

Thanks for the great Laravel package!

**Comment by osiset** [comment]
@justenh You'd have to dig into the test folder here. Essentially I have a class which extends the API class, and overwrites the rest/graph request method to return a JSON file instead of actually doing the call.

As for accessing via cron job, just get the shop with Eloquent, and use the api method, like:

```
$shop = User::where('shopify_domain', $shop)->first();
$api = $shop->api();
$info = $api->rest('GET', '/admin/shop.json')['body']->shop;
```
