### ISSUE TITLE
419 error only in Chrome Incognito mode (POST request)

### ISSUE THREAD

**Issue by APdevelopments** [osiset/laravel-shopify#751]
I use Laravel 5.8 version.
My form is:

    <form method="POST" action="store_catalog" accept-charset="UTF-8" enctype="multipart/form-data">
      
      {{ csrf_field() }}

when I submit my form I got 419 error but _token is sent:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/yE2oK.png

All this works perfectly in standard Chrome mode but this won't work in incognito mode. I also think that doesn't work in some other browsers but I didn't check.

Why I got 419 error in Incognito mode and how to solve it?

**Comment by muhammadasfar** [comment]
@APdevelopments Yes, You are right. I am also facing this same issue. I have also checked in the Mozilla Firefox (Normal and Private mode) and the issue is the same as you stated above.

**Comment by APdevelopments** [comment]
I'm using osiset 12v and laravel 5.8

Reported by Shopify review team so it will be a problem if i dont fix it

**Comment by muhammadasfar** [comment]
As I investigated, the issue is due to the same site cookies param remain the same. (false, lax). When I change these values the POST call is working fine from config/session.php in Laravel.

The package is not performing the same site for POST calls.

My app is also performing CRUD using jQuery Ajax and I am facing this issue. Same site cookies for POST calls are as in the below screenshot.

![same-site-for-post-ajax-call](https://user-images.githubusercontent.com/38552865/112827586-fb00bd80-90a7-11eb-906b-35f5dfb11f3e.png)

@APdevelopments please check your app POST call in the browser as in the above screenshot.

**Comment by darrynten** [comment]
I suggest switching to using the JWT provided by Shopify.

**Comment by APdevelopments** [comment]
![image](https://user-images.githubusercontent.com/10516734/112894932-ca874680-90dc-11eb-8fab-9967913b66b6.png)

**Comment by APdevelopments** [comment]
Whats changes I need to do to config/sessions.php?

**Comment by APdevelopments** [comment]
I also tried:

![image](https://user-images.githubusercontent.com/10516734/112896320-8d23b880-90de-11eb-867c-b48f3d830418.png)

**Comment by APdevelopments** [comment]
WOrth trying to replace POST with GET request? Or to use AJAX instead of simple form submit using HTML

**Comment by darrynten** [comment]
@APdevelopments [Shopify no longer accepts cookie based apps onto the app store since March 8th](https://shopify.dev/changelog/all-embedded-apps-submitted-for-app-review-are-required-to-adopt-session-tokens), and is going to be disabling apps that use cookies in the near future, so it's time to move on from server side sessions.

You should drop cookies altogether and use the JWT Shopify provide on the frontend with the `auth.token` middleware instead of the session based one.

Just add the JWT to an `Authorization` header as a `bearer` token and you'll be good to go when posting to `auth.token` routes.

**Comment by APdevelopments** [comment]
Its supported by this library? Or its laravel based task?

**Comment by darrynten** [comment]
@APdevelopments it is supported in this library, just change your middleware from `auth.shop` to `auth.token` and send through the JWT Shopify provides you on the frontend in the `Authorization` header.

**Comment by APdevelopments** [comment]
I change in config/auth.php 

 | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'token',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],


but I got error:


![image](https://user-images.githubusercontent.com/10516734/113028967-2d83e680-918c-11eb-9869-810866395c11.png)

In which file I need to change session to token ? Please help!

**Comment by darrynten** [comment]
Don't change it in `config/auth.php` - you must change the middleware on the route (e.g. `router/web.php`)

**Comment by APdevelopments** [comment]
so I need to change Route::get('/', 'ShopifyController@home')->middleware(['auth.shopify', 'billable'])->name('home'); to

Route::get('/', 'ShopifyController@catalogs')->middleware(['auth.token', 'billable'])->name('home');

???

**Comment by APdevelopments** [comment]
Should I remove 'auth' at all from my route /store_catalog or just to make an exception?

**Comment by osiset** [comment]
Cleanup... Closing for now, cookies are removed in v17.0.0 additionally CSRF is to be disabled for v17.0.0
Re-open if still and issue.
Thanks!
