### ISSUE TITLE
graphQL Query not working Correctly !

### ISSUE THREAD

**Issue by Gouenji10** [osiset/laravel-shopify#759]
Hey there !
I am having trouble running query in graphQl. 
I am using this query to get some orders filtered.

`$query = '{
      orders(first: 20, query:"Beauty Tee") {
          edges {
          node {
              id
              name
              customer {
              id
              firstName
              lastName
              }
              lineItems(first: 5) {
              edges {
                  node {
                  id
                  title
                  }
              }
              }
          }
          }
      }}';
  $result = $shop->api()->graph($query);
  print_r($result['body']);`

I got the expected result in the shopify graplQl app. Below is the screenshot from the app. 
![image](https://user-images.githubusercontent.com/28804343/114293252-46f23000-9ab4-11eb-884d-c3b3b88d684f.png)

But to my expectation here is the result screenshot from the code output.
![image](https://user-images.githubusercontent.com/28804343/114293276-815bcd00-9ab4-11eb-9afc-a89a96f6c595.png)

I am using 
"php": "7.4",
"laravel": "7"
 "osiset/laravel-shopify": "^16.0"

**Comment by derickRenwick** [comment]
Hey @Gouenji10 I am having the same, issue except the response is returning HTML with the code to do the redirect back to Shopify.

This only started yesterday as well after updating to v16, I'm not sure if that is the sole cause or a coincidence but I wanted to add to the thread as I am having issues suddenly as well.

I followed the upgrade guides but I know there is ongoing development on the Auth Refactoring #744 so maybe this is a side effect? Not sure but very odd since the query was working previously and was not modified during the upgrades.

I haven't tried querying through graphiql or anything yet but I will to see if I get the correct response via that method.

**Comment by derickRenwick** [comment]
My query works correctly when testing with a local version of the app using Homestead (w/ HTTPS), @Gouenji10 are you using Heroku? 

My Heroku version of the app is having issues with the graphql query so I wonder if its the same for you. Does your app work locally but break on a server?

**Comment by Gouenji10** [comment]
@derickRenwick  I am not using Heroku. I am working directly on the  stagging version of the server.

**Comment by derickRenwick** [comment]
@Gouenji10 Ok thanks for the extra info. My issue was resolved after fixing another bug related to some js on the same page. Not sure if that was the direct solution or I had done something else in the process but its working correctly now.

**Comment by Gouenji10** [comment]
@derickRenwick  I don't have any JS confilict. I am just simply trying to get the data by using graphQL from the controller and passing the value to view. For testing on the shopifyQL App the query works perfectly, but we trying to query with the graphQL api it doesn't show any result.

**Comment by Kyon147** [comment]
Closing as stale issue.
