### ISSUE TITLE
Issue while installing on APP on store.

### ISSUE THREAD

**Issue by ingalesachin7** [osiset/laravel-shopify#866]
I have upgraded to 17.0.0 for Removal of dependency on cookies,
I try to install the app on the store,  after the permissions page while installing actions..
getting an authentication error
Exception
Variable $topic of type WebhookSubscriptionTopic! was provided invalid value

after refresh
Osiset\ShopifyApp\Exceptions\MissingAuthUrlException
Missing auth URL

Please help anyone to resolve this...Is something is missing while upgrading.?

**Comment by mattias** [comment]
I can confirm I have the same issue after upgrading to 17.0.0.

At first I had the same issue as #863 so I thought I'd try to reinstall the app. But instead I got this issue.

I use IntertiaJS if this is of interest. Not sure if it all depends on that decision. 
And not sure if I need to do anything with the session token? InertiaJS's documentation has nothing on it since it "should just work automagically".


As for the #863 issue, it just keeps refreshing the authentication page over and over. Probably because of the session token. If anyone knows what needs to be done with InertiaJS please let me know. :)


As for this issue, investigating while writing this, it seems there was a change for webhooks that changes the topic name.
For example in rest we have "app/uninstalled" but in the new change which uses graphql it is "APP_UNINSTALLED".
See more here: https://shopify.dev/api/admin/graphql/reference/events/webhooksubscriptiontopic

Updated in config/shopify-app.php to use the new topic names for webhooks.

**Comment by ingalesachin7** [comment]
Thanks, @mattias,
I have updated the webhooks  topic name to "APP_UNINSTALLED" the installation issues get solved,
but now when I used Auth::user() in the controller,
getting an error: **Session token is malformed.**

**Comment by squatto** [comment]
I just updated [the "Creating Webhooks" wiki page](https://github.com/osiset/laravel-shopify/wiki/Creating-Webhooks) to reflect the requirement to use GraphQL webhook topics.

You can find all valid GraphQL webhook topics [here](https://shopify.dev/api/admin/graphql/reference/events/webhooksubscriptiontopic).

**Comment by squatto** [comment]
I submitted #868 to add backward compatibility for pre-v17 webhook topics. Your existing webhooks will continue to work, and you'll be able to use REST-style topics (`resource/event`) or GraphQL-style topics (`RESOURCE_EVENT`) going forward.

**Comment by osiset** [comment]
Pushed patch for above. Thanks @squatto

**Comment by squatto** [comment]
My pleasure! That should hopefully avoid some upgrade pains 👍🏻
