### ISSUE TITLE
Session token is invalid

### ISSUE THREAD

**Issue by arpit-panther** [osiset/laravel-shopify#895]
Hello,
I just Upgrade My osiset version 15 to 17.0.1
- as Upgrading doc mention. i follow all the steps. and i got this error in get api call.

error: "Session token is invalid."
 
i also tried with window.sessionToken as per doc mention. but when i tried to use this. i can not get result.

when i console window.sessionToken its show 'undefined'.

if i remove verify.shopify middle-ware then i didn't get this error.

FYI. i am using React-SPA. and for the API call i am using axios.
@osiset

**Comment by arpit-panther** [comment]
Hello,
any one found solution of this. ?
after upgrading to version 17.0.1 my app is crashed and not working any thing.

can any one please help me with this or any suggestion according to this ?

**Comment by ajaymakwana888** [comment]
Hello,
Any updates on this issue.

I'm getting the same issue.  `window.sessionToken` is 'undefined' sometimes in API call.

**Comment by osiset** [comment]
I can't replicate this. I don't get undefined at any time. It constantly updates properly. Not sure what I can do to help without info.

**Comment by Kyon147** [comment]
I've found there is a race condition if you try and grab the session token too quickly. You get a session token is invalid because you are trying to get the `window.sessionToken` object too soon on page render.

The solve is fairly simple, just delay your request byt 50.100ms and let the blade file grab the token. Alternatively you can use something like an interceptor in axios to always get the token before any request. . 

Here's my example:

```
axios.interceptors.request.use(function (config) {
    return utils.getSessionToken(window['app-bridge-app']) // requires a Shopify App Bridge instance
        .then((token) => {
            console.log('axios token');
            // Append your request headers with an authenticated token
            config.headers.Authorization = `Bearer ${token}`;
            return config;
        });
});
```
