### ISSUE TITLE
How do I switch to non-bridge mode？

### ISSUE THREAD

**Issue by jackwiy** [osiset/laravel-shopify#914]
AppBridge Installation successful and work good.
But I want to switch to non-bridging mode.
When I open app in shopify list, Stay on the following token page.

https://domin_xxx.com/authenticate/token?shop=test_xxx.myshopify.com&target=%2Fhome%3Fhost%3DZWx1by10ZXN0OC5teXNob3BpZnkuY29tL2FkbWlu

Specific Detail:

URL
```
APP URL: https://domin_xxx.com/home
Redirect URL: https://domin_xxx.com/authenticate
```

.env (The only thing that changed, it can't work.)
```
SHOPIFY_APPBRIDGE_ENABLED=false
```

```
Route::group(['prefix' => config('shopify-app.prefix'), 'middleware' => ['verify.shopify', 'billable']], function () {
    //Home
    require __DIR__ . '/../routes/app/home.php';
});
```

Stay on the following token.blade.php page.
![image](https://user-images.githubusercontent.com/5044378/126429622-6b1929b2-ae1e-45eb-8acf-ef2dd04074ed.png)

**Comment by enmaboya** [comment]
the app is currently tethered to the app bridge

**Comment by osiset** [comment]
Because of the tokens we need app bridge. Correct, it's tied to it .

**Comment by jackwiy** [comment]
@osiset 

Thank you for your reply.

**Comment by xplodedthemes** [comment]
Hi @osiset, will the package support non embedded apps again ? 

Basically, my app has 2 sections. One is embedded, and the other one is not. In the embedded section, I need to click a link that opens an external Full screen view (an editor that contains an iframe preview of the shop frontend).

This used to work fine before updating to v17, now, whenever I click on the external link, it authenticates again then redirect to the embedded app instead of opening in full screen. 

There is no way of using regular auth only for the non embedded part ?
