### ISSUE TITLE
How to config laravel app subdomains project in shopify? 

### ISSUE THREAD

**Issue by ngoducnhuiit** [osiset/laravel-shopify#998]
I have a problem asking if I have the main domain with many laravel projects inside how can I create a Shopify app using a domain with many different laravel project routes or is there any reconfigurable path to the laravel project on the server. My English is not very good, hope you can understand my question. Sincerely thank you .

how can I configure the App URL on Shopify with one main domain and multiple subdomains created with different laravel projects? The domain example is :

https://domain.com/shopifyapp/laravelapp1

https://domain.com/shopifyapp/laravelapp2

**Comment by Kyon147** [comment]
Hi @ngoducnhuiit 

This is not really the place for Laravel/Dev Ops support. It is possible to run the app in a folder which there are some documentation on the internet for https://learnwithdaniel.com/2021/03/run-laravel-project-in-subfolder-apache/

Usually it is best to run an app on it's own domain or subdomain because you can deal with the routing and requests much more specifically.
